### PUBLISH
publish_snapshot:
  stage: publish
  script:
    - SNAPSHOT_VERSION=$(echo ${CI_COMMIT_BRANCH} | cut -f2 -d'-')
    - echo "${SNAPSHOT_VERSION}-SNAPSHOT" > .dev-version || exit 1
    - sh gradlew publish
  environment:
    name: development
  only:
    - /^release-.*$/
  when: on_success


## only tags
# publish to gitlab before release to distibutor
publish_release:
  stage: publish
  script:
    - bash $SCRIPTS_DIR/genSemVer.sh release > .dev-version || exit 1
    - sh gradlew publish
  environment:
    name: production
  only:
    - tags
  when: on_success

### REPLAY
gitlab_release:
  stage: replay
  image: registry.gitlab.com/gitlab-org/release-cli
  tags:
    - docker
  script:
    - release-cli create --name "v$(cat .dev-version)" --description "$CI_COMMIT_MESSAGE" --tag-name $(cat .dev-version) --ref $CI_COMMIT_SHA
  only:
    - tags
  when: on_success

include:
  - project: client/labymod4/common-scripts
    ref: master
    file: .gitlab-ci-template.yml

