# publish snapshots if pushed to release-X.X.X branch
publish_snapshot:
  stage: deploy
  script:
    - export VERSION="$(echo -ne $CI_COMMIT_REF_NAME | cut -d"-" -f2)-SNAPSHOT" || exit 1
    - sh gradlew publish
  environment:
    name: development
  only:
    - /^release-.*$/
  when: on_success

# publish release if tag is pushed
publish_release:
  stage: deploy
  script:
    - export VERSION="${CI_COMMIT_TAG}" || exit 1
    - sh gradlew publish
  environment:
    name: production
  only:
    - tags
  when: on_success
