### PUBLISH
publish_prerel_snapshot:
  stage: publish
  script:
    - bash $SCRIPTS_DIR/branchingPreCheck.sh
    - bash $SCRIPTS_DIR/genSemVer.sh prerel SNAPSHOT > .dev-version || exit 1
    - sh gradlew
      -Plabyfy_publish_url=$LABYFY_PUBLISH_URL
      -Plabyfy_publish_token=$LABYFY_PUBLISH_TOKEN
      -Partifactory_contextUrl=$artifactory_contextUrl
      -Partifactory_password=$artifactory_password
      -Partifactory_user=$artifactory_user
      artifactoryPublish --stacktrace
  environment:
    name: development
  only:
    - develop
  when: on_success

## only tags
# publish to artifactory before release to distibutor
publish_release:
  stage: publish
  script:
    - bash $SCRIPTS_DIR/branchingPreCheck.sh
    - bash $SCRIPTS_DIR/genSemVer.sh release > .dev-version || exit 1
    - sh gradlew
      -Plabyfy_publish_url=$LABYFY_PUBLISH_URL
      -Plabyfy_publish_token=$LABYFY_PUBLISH_TOKEN
      -Partifactory_contextUrl=$artifactory_contextUrl
      -Partifactory_password=$artifactory_password
      -Partifactory_user=$artifactory_user
      artifactoryPublish --stacktrace
  environment:
    name: development
  only:
    - tags
  when: on_success

### REPLAY
gitlab_release:
  stage: replay
  image: registry.gitlab.com/gitlab-org/release-cli
  tags:
    - docker
  script:
    - release-cli create --name "v$(cat .dev-version)" --description "$CI_COMMIT_MESSAGE" --tag-name $(cat .dev-version) --ref $CI_COMMIT_SHA
  only:
    - tags
  when: on_success

include:
  - project: client/labymod4/common-scripts
    ref: master
    file: .gitlab-ci-template.yml

