name : Java CI with Gradle

on :
  push :
    tags :
      - '**'
jobs :
  build :
    runs-on : ubuntu-latest

    steps :
      - name : Cache multiple paths
        uses : actions/cache@v2
        with :
          path : |
            ~/.gradle/caches/flint-gradle
            ./**/build/flint
          key : jdk-8-flint-gradle-plugin

      - uses : actions/checkout@v2

      - name : Set up JDK 1.8
        uses : actions/setup-java@v1
        with :
          java-version : 1.8

      - name : Grant execute permission for gradlew
        run : chmod +x gradlew

      - name : Get tag name
        id : get_tag_name
        run : echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name : Build with Gradle
        run : ./gradlew build --full-stacktrace
        env :
          VERSION : ${{ steps.get_tag_name.outputs.VERSION }}
          FLINT_DISTRIBUTOR_BEARER_TOKEN : ${{ secrets.FLINT_DISTRIBUTOR_BEARER_TOKEN }}
          FLINT_DISTRIBUTOR_URL: ${{ secrets.FLINT_DISTRIBUTOR_URL }}
      - name: Publish with Gradle to maven repository
        run : ./gradlew publish --full-stacktrace
        env:
          VERSION : ${{ steps.get_tag_name.outputs.VERSION }}
          FLINT_DISTRIBUTOR_BEARER_TOKEN : ${{ secrets.FLINT_DISTRIBUTOR_BEARER_TOKEN }}
          FLINT_DISTRIBUTOR_URL: ${{ secrets.FLINT_DISTRIBUTOR_URL }}
